> # **Dependecies**

In [36]:
#!pip install neattext
#!pip install re

In [1]:
import pandas as pd               #python package for data analysis
import numpy as np                #python package for handling arrays 
import re                         #python package for dealing with regular expressions
import neattext as nt             #python package for some regex and text cleaninig purposes

> # **Spacy Language Models**

In [2]:
# should have python 3.6
#!pip install spacy
#!pip install scispacy
#spacy donwnload en_core_web_lg
#spacy download en_ner_bc5cdr_md

In [3]:
import spacy                            #premium python package for NLP
nlp=spacy.load('en_core_web_lg')        #importing spacy large language model
#import scispacy                        #scientific spacy (scispacy) for biomedical uses
#sci_nlp=spacy.load(("en_ner_bc5cdr_md") #importing bc5cdr medium model for detection of diseases and drugd

c:\users\zee tech\appdata\local\programs\python\python39\lib\site-packages\spacy\util.py:877: UserWarning: [W095] Model 'en_core_web_lg' (3.2.0) was trained with spaCy v3.2 and may not be 100% compatible with the current version (3.4.4). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)

> # **Regular Expressions**

In [73]:
ind_passport_regex=r'^[A-Z]{2}\d{7}[A-Z]$'
maldv_passport_regex=r'^[A-Z]\d{6}$'
china_passport_regex=r'^[A-Z]\d{8,9}$'
indonsh_passport_regex=r'^[A-Z]\d{9}$'
pak_passport_regex=r'^[A-Z]{2}\d{7}[A-Z]{3}$'

In [74]:
ind_natid_regex=r'^\d{12}$'
pak_natid_regex=r'^\d{5}\d{7}\d$'
sri_natid_regex=r'^\d{9}[VvXx]$'
bangla_natid_regex=r'^\d{4}\d{2}\d{2}\d{4}\d{5}$'
nepal_natid_regex=r'^\d{10}\d{3}$'

In [75]:
ssn_regex = r'^\d{3}-\d{2}-\d{4}$'
china_national_id_regex = r'^[A-Z]\d{17}$'
india_national_id_regex = r'^\d{12}$'
japan_national_id_regex = r'^\d{12}$'
pakistan_national_id_regex = r'^\d{13}$'
philippines_national_id_regex = r'^\d{12}$'
ifsc_regex="^[A-Z]{4}0[A-Z0-9]{6}$"

In [168]:
emails=[]
phone_no=[]
names=[]
drugs=[]
diseases=[]
national_ids=[]
passport_no=[]
gpe=[]
locations=[]
urls=[]
zip_codes=[]
orgs=[]
ip_addresses=[]
mac_addresses=[]
ssn=[]
master_visa_cards=[]
ifsc=[]
fb_profiles=[]
telegram_profiles=[]
twitter_profiles=[]
linkedin_profiles=[]
insta_profiles=[]

> # **Critical PII**

In [169]:
def extract_critical_pii(data):
    '''
    This function extracts critical PII
    '''
    raw_data=data
    emails.extend(re.findall(re.compile(r'[\w\.-]+@[\w\.-]+', re.UNICODE),raw_data))
    phone_no.extend(re.findall(re.compile(r'[\+\(]?[1-9][0-9 .\-\(\)]{8,}[0-9]',re.UNICODE),raw_data))
    #phone_no=[ph_no for ph_no in phone_no if len(ph_no)<=15]
    doc=nlp(data)
    for ent in doc.ents:
        if ent.label_=='PERSON':
            names.append(ent.text)
  #  doc=sci_nlp(data)
 #   for ent in doc.ents:
 #       if ent.label_=='DISEASE':
 #           dieases.append(ent.text)
 #       else:
 #           drugs.append(ent.text)

In [170]:
phone_no=[ph_no for ph_no in phone_no if len(ph_no)<=15]

> # **Sensitive PII**

In [171]:
def extract_sensitive_pii(data):
    '''
    This function extracts sensitive PII
    '''
    raw_data=data
    for element in data.split('$'):
        ssn.extend(re.findall(r'^\d{3}-\d{2}-\d{4}$',element.strip()))
        ifsc.extend(re.findall(ifsc_regex,element.strip()))
        master_visa_cards.extend(re.findall(re.compile(r'(?:(?:(?:\d{4}[- ]?){3}\d{4}|\d{15,16}))',re.UNICODE),element.strip()))
        master_visa_cards.extend(re.findall(re.compile(r'5[1-5]\d{2}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}',re.UNICODE),element.strip()))
        passport_no.extend(re.findall(ind_passport_regex,element.strip()))
        passport_no.extend(re.findall(maldv_passport_regex,element.strip()))
        passport_no.extend(re.findall(china_passport_regex,element.strip()))
        passport_no.extend(re.findall(indonsh_passport_regex,element.strip()))
        passport_no.extend(re.findall(pak_passport_regex,element.strip()))
        national_ids.extend(re.findall(ind_natid_regex,element.strip()))
        national_ids.extend(re.findall(pak_natid_regex,element.strip()))
        national_ids.extend(re.findall(sri_natid_regex,element.strip()))
        national_ids.extend(re.findall(bangla_natid_regex,element.strip()))
        national_ids.extend(re.findall(nepal_natid_regex,element.strip()))
        urls.extend(nt.extract_urls(raw_data))
        for url in urls:
            if 'facebook' in url:
                fb_profiles.append(url)
                del urls[url]
            if 't.me' in url:
                telegram_profiles.append(url)
                del urls[url]
            if 'linkedin' in url:
                linkedin_profiles.append(url)
                del urls[url]
            if 'twitter' in url:
                twitter_profiles.append(url)
                del urls[url]
            if 'instagram' in url:
                insta_profiles.append(url)
                del urls[url]

    doc=nlp(raw_data)
    for ent in doc.ents:
        if ent.label_=='GPE':
            gpe.append(ent.text)
        if ent.label_=='LOC':
            locations.append(ent.text)

NameError: name 'doc' is not defined

> # **Quasi PII**

In [172]:
def extract_quasi_pii(data):
    '''
    This function extracts Quasi PII
    '''
    for element in data.split('$'):
        ip_addresses.extend(re.findall(r"[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}",element.strip()))
        mac_addresses.extend(re.findall(r'^(?:[0-9A-Fa-f]{2}[:-]){5}(?:[0-9A-Fa-f]{2})$',element.strip()))
    doc=nlp(data)
    for ent in doc.ents:
        if ent.label_=='ORG':
            orgs.append(ent.text)

> # **Classification**

In [173]:
critical_df=pd.DataFrame()
sensitive_df=pd.DataFrame()
quasi_df=pd.DataFrame()

In [174]:
def classification():
    '''
    This function collect all the extracted data and classify into their respective categories
    '''
   # critical_pii={'Names':names,'Emails':emails}
    critical_df=pd.DataFrame([names,emails,phone_no,diseases,drugs],index=['Names','Emails','Phone No','Diseases','Drugs'])
    sensitive_df=pd.DataFrame([ssn,master_visa_cards,ifsc,national_ids,passport_no,telegram_profiles,
                           twitter_profiles,linkedin_profiles,insta_profiles,urls,gpe,locations],
                           index=['SSN','Master Visa Cards','IFSC','National ID','Passport No',
                                 'Telegram Profiles','Twitter Profiles','LinkedIn Profiles',
                                 'Instagram Profiles','URLs','Geographic Locations','Locations'])
    quasi_df=pd.DataFrame([orgs,ip_addresses,mac_addresses],index=['Organizations','IP Addresses','MAC Addresses'])
    return critical_df.T,sensitive_df.T,quasi_df.T

> # **Extract PII**

In [175]:
def extract_PII(df):
    '''
    This function receives a dataframe of csv file and format the dataframe and pass to each 
    of critical,sensitive and quasi pii extraction functions.
    '''
    all_data=df.values
    for value in all_data:
        data=' $ '.join(value)
        extract_critical_pii(data)      #passing data to critical pii extraction function
        extract_sensitive_pii(data)     #passing data to sensitive pii extraction function
        extract_quasi_pii(data)         #passing data to quasi pii extraction function

In [176]:
df=pd.read_csv('People_data.csv')    #reading the csv file

In [177]:
df=df.astype('str')

In [178]:
extract_PII(df[0:10])                   #calling extract_PII function

In [179]:
critical_df,sensitive_df,quasi_df=classification()

In [180]:
critical_df

,Names,Emails,Phone No,Diseases,Drugs
0,Sarah Cooper,Alex.Lopez@testDomain.com,18-11-1972,None,None
1,Joseph Ways,graymichael@example.com,191) 496 0268,None,None
2,William Lewis,Kathryn.Garrett@testDomain.com,16-09-1999,None,None
3,Rasmussen Brooks Suite,patricia00@example.com,+44(0)8081570861,None,None
4,Heather Stephenson,Mr..Alec@testDomain.com,114) 4960654,None,None
5,Jonathan Crest,tiffany89@example.com,808 157 0941,None,None
6,Lawrenceland,Craig.Turner@testDomain.com,+44(0)131 496 0676,None,None
7,Audrey Phelps,garciateresa@example.org,23-07-1984,None,None
8,John Burgess,Jacqueline.Tate@testDomain.com,+44131 4960030,None,None
9,Vargas Dale,ramirezcaroline@example.org,30-07-1993,None,None
10,Robert Camacho,Joshua.Lawrence@testDomain.com,1414960117,None,None
11,Jason Fields Apt,mariaberry@example.net,24-02-1985,None,None
12,Port Williamfurt,Debra.Jensen@testDomain.com,808) 157 0565,None,None
13,Amy Whitaker,hilltyler@example.org,10-01-1996,None,None
14,Kyle Squares,Rachel.Fernandez@testDomain.com,115) 4960537,None,None
15,West Cassie,nicholas96@example.org,+44(0)141 496 0726,None,None
16,Richard Carr,Jessica.Davis@testDomain.com,None,None,None
17,Ryan Cape,whitetammy@example.com,None,None,None
18,Karen Wilson,Matthew.Brooks@testDomain.com,None,None,None
19,East Alexis,rmiller@example.org,None,None,None

In [181]:
sensitive_df

,SSN,Master Visa Cards,IFSC,National ID,Passport No,Telegram Profiles,Twitter Profiles,LinkedIn Profiles,Instagram Profiles,URLs,Geographic Locations,Locations
0,None,None,None,None,None,None,None,None,None,https://evans-vincent.com/,Yemen,None
1,None,None,None,None,None,None,None,None,None,https://evans-vincent.com/,Washington,None
2,None,None,None,None,None,None,None,None,None,https://evans-vincent.com/,New Jasonhaven,None
3,None,None,None,None,None,None,None,None,None,https://evans-vincent.com/,Arkansas,None
4,None,None,None,None,None,None,None,None,None,https://evans-vincent.com/,Cambodia,None
...,...,...,...,...,...,...,...,...,...,...,...,...
145,None,None,None,None,None,None,None,None,None,http://wood-pitts.info/,None,None
146,None,None,None,None,None,None,None,None,None,http://wood-pitts.info/,None,None
147,None,None,None,None,None,None,None,None,None,http://wood-pitts.info/,None,None
148,None,None,None,None,None,None,None,None,None,http://wood-pitts.info/,None,None
149,None,None,None,None,None,None,None,None,None,http://wood-pitts.info/,None,None

In [182]:
quasi_df

                 Organizations IP Addresses MAC Addresses
0                    Clarkfurt         None          None
1  SD 37952 $ 68442 $ Nashberg         None          None
2                           MA         None          None
3                Romero Summit         None          None
4                           AZ         None          None
5       $ Netherlands Antilles         None          None
6  DE 31059 $ 68175 $ New Eric         None          None
7               441 Ochoa Lock         None          None
8            Millsstad $ Maine         None          None
9       $ Netherlands Antilles         None          None

> # **Saving the Extacted Results**

In [167]:
critical_df.to_csv('critical_pii.csv')
sensitive_df.to_csv('sensitive_pii.csv')
quasi_df.to_csv('quasi_pii.csv')