In [5]:
import pandas as pd
import numpy as np

In [69]:
divorce_df=pd.read_excel('Divocre Rata Analysis.xlsx')

In [70]:
divorce_df=divorce_df.drop('Woman\'s Job Type',axis=1)

In [71]:
divorce_df.dropna(inplace=True)

In [72]:
divorce_df

,Submission Date,Man's City,Woman's City,Man Age,Woman Age,Man's Education,Woman's Education,Man's Monthly Income,Woman's Working Status,Family System,...,No. of children,"Boy drugs leta tha k ni (yes, no)",Marriage Type,Reason of Divorce,Reasons from Man Sdie,Reasons from Woman Side,Span of Marriage Life,Marriage No. of Male,Submission ID,Marriage No. of Female
0,2023-01-12 12:26:53,Multan,Multan,22.0,18.0,Primary,Primary,20000,House wife,Combine,...,0.0,No,Arrange,"death threats to after marriage, persecution o...",intervention of wife family,"dead threats to wife, persecution on wife",1.0,1,5.493176e+18,1
1,2023-01-12 12:38:57,Multan,Multan,24.0,24.0,Metric,Graduation,90000,Job holder,Seprarate,...,0.0,No,Love,"job lost, no child, financial problems",no child,"financial problems,, job lost",4.0,1,5.493183e+18,1
5,2023-01-12 19:22:39,Multan,Sargodha,32.0,27.0,Mphill English,FSC,90000,House wife,Combine,...,0.0,No,Arrange,No Child.,no child,sarcasm of husband family,3.0,1,5.493426e+18,1
6,2023-01-12 20:20:57,Kot Addu,Multan,23.0,26.0,F.Sc,Mphil,20000,Job holder,Separate,...,0.0,No,Love,"no child, black magic on boy, no child, black ...","no child, black magic on husband",sarcasm of husband family,1.0,1,5.493461e+18,1
11,2023-01-14 17:19:09,Lahore,Lahore,23.0,25.0,Matric,5th class,25000,House wife,Combine,...,0.0,No,Love,dont know,household problems,family issues,1.0,1,5.495079e+18,1
15,2023-01-14 20:48:54,Multan,Multan,25.0,20.0,Metric,Middle,30000,House wife,Combine,...,0.0,No,Arrange,"no child, black magic on man","no child, black magic on husband","husband misbehavior, sarcasm of husband family",3.0,1,5.495205e+18,1
17,2023-01-14 21:25:56,Multan,Multan,27.0,18.0,Matric,Primary,30000,House wife,Combine,...,1.0,Yes,Arrange,Boy ka accident hua jis ki waja se uski yaad d...,selfish wife,"mental condition of husband, financial problem...",4.0,1,5.495228e+18,1
19,2023-01-14 21:36:13,Multan,Multan,32.0,27.0,Matric,Middle,60000,House wife,Combine,...,2.0,No,Arrange,Larai jhagra aur kharcha nhi deta tha boy jis ...,extra marital affairs of wifle,"financial problems, household problems",10.0,1,5.495234e+18,1
20,2023-01-14 21:44:37,Multan,Multan,30.0,28.0,No education,No education,10000,House wife,Combine,...,4.0,No,Arrange,"Boy kamata nhi tha, kharchyy ka problem tha ji...",slovenly man,"financial problems,household problemns",12.0,1,5.495239e+18,1
21,2023-01-14 21:50:22,Multan,Multan,40.0,37.0,Matric,Matric,60000,House wife,Combine,...,1.0,No,Arrange,"Inka watta satta tha, aur phr larky ko shakk t...",extra merital affairs,"extra merital affairs, jobless husband",8.0,1,5.495242e+18,1